micronaut:
  server:
    port:
      9999
  application:
    name: helloworld
  security:
    enabled: false
#    endpoints:
#      login:
#        enabled: true
#    authentication: bearer
#    token:
#      jwt:
#        signatures:
#          secret:
#            generator:
#              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:asklfhasiogfaifilasbfuuvasguofsgbaslfaslfbvailgfiasbksjl}"'
datasources:
  default:
#    url: jdbc:h2:mem:db;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:~/db/dbDev
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update

test: "I'm a test"